{% set version = "1.7.0" %}

package:
  name: varlociraptor
  version: {{ version }}

build:
  number: 0

source:
  url: https://github.com/varlociraptor/varlociraptor/archive/v{{ version }}.tar.gz
  sha256: 151e5bc94a60ca84818a2a3b2d630acbb804489d9961ac6d29b24be294092b44

requirements:
  build:
    - rust >=1.30
    - clangdev
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config
  host:
    - gsl
    - openssl
    - openblas
    - libcblas
    - zlib
    - bzip2
    - xz
    - clangdev
    - blis
  run:
    - gsl
    - openssl
    - openblas
    - libcblas
    - zlib
    - bzip2
    - xz
    - blis

test:
  commands:
    - varlociraptor -h

about:
  home: https://varlociraptor.github.io
  license: GPLv3
  license_family: GPL
  summary: Flexible, uncertainty-aware variant calling with parameter free filtration via FDR control.
