{% set version = "2.2.12" %}
{% set sha256 = "bfda0f0640addb3cc22fa7ccd914aef6db0a14c91a09861d687dcfb77f3c2fb1" %}

package:
  name: pkiss
  version: {{ version }}


source:
  sha256: {{ sha256 }}
  url: https://github.com/jlab/fold-grammars/archive/{{ version }}.tar.gz

build:
  number: 3
  skip: True # [osx]

requirements:
  host:
    - perl
    - bellmans-gapc >=2020.01.08
  run:
    - perl
    - bellmans-gapc >=2020.01.08

test:
  commands:
  - echo "UGGCCGGCAUGGUCCCAGCCUCCUCGCUGGCGCCGGCUGGGCAACAUUCC" | pKiss --mode=probs &> /dev/null

about:
  home: https://bibiserv.cebitec.uni-bielefeld.de/pkiss
  license: 'GPLv3+'
  license_file: LICENSE
  summary: 'RNA secondary structure prediction including K-type and kissing hairpin- pseudoknots.'

extra:
  identifiers:
    - doi:10.1007/978-3-642-15294-8_5
    - doi:10.1093/bioinformatics/btu649
